name: Publish

on:
  push:
    tags: [ "v*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # - id: prep
    #   run: |
    #     DOCKER_IMAGE=gcr.io/justfaas/gateway
    #     VERSION=${GITHUB_REF#refs/tags/}
    #     VERSION=${VERSION#v}
    #     TAGS="${DOCKER_IMAGE}:${VERSION}"
    #     if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    #       MINOR=${VERSION%.*}
    #       MAJOR=${MINOR%.*}
    #       TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
    #     fi
    #     echo ::set-output name=version::${VERSION}
    #     echo ::set-output name=tags::${TAGS}
    - id: prep
      run: |
        DOCKER_IMAGE=gcr.io/justfaas/gateway
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=tags::${TAGS}
    - name: Build and push Docker image for Raspberry Pi
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: ${{ steps.prep.outputs.tags }}
        # tags: |
        #   ghcr.io/justfaas/gateway:latest
        #   ghcr.io/justfaas/gateway:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
        secrets: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changes }}
